version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: agency_db_container
    restart: always
    environment:
      MYSQL_DATABASE: agency_db
      MYSQL_ROOT_PASSWORD: Manjil@1982
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    image: sand58957/sandeepit:latest
    container_name: sandeeepit_web
    command: >
      sh -c "echo 'Waiting for database...' &&
             sleep 10 &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 core.wsgi:application"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mysql_data:
