services:
  db:
    image: mysql:8.0
    container_name: agency_db_container
    restart: always
    environment:
      MYSQL_DATABASE: agency_db
      MYSQL_ROOT_PASSWORD: Manjil@1982
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: agency_redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    image: sand58957/sandeepit:latest
    container_name: sandeeepit_web
    command: >
      sh -c "echo 'Waiting for database...' &&
             sleep 10 &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 core.wsgi:application"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

volumes:
  mysql_data:
