version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: agency_db_container
    restart: always
    environment:
      MYSQL_DATABASE: agency_db
      MYSQL_ROOT_PASSWORD: Manjil@1982
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    image: sand58957/sandeepit:latest
    container_name: sandeeepit_web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 core.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - DB_NAME=agency_db
      - DB_USER=root
      - DB_PASSWORD=Manjil@1982
      - DB_HOST=db
      - DB_PORT=3306
      - WHITENOISE_CONFIG=True
    depends_on:
      - db

volumes:
  mysql_data:
